name: file_type
version: 1.0.5
description: Gets the type of a file
author: Neel Kamath <neelkamath@icloud.com>
homepage: https://github.com/neelkamath/file-type

dev_dependencies:
  link_checker: ^1.1.0
  test: ^1.3.0

environment:
  sdk: '>=2.0.0-dev.65.0 <3.0.0'